---
- name: metz's machine configuration
  hosts: localhost
  connection: local

  vars:
    packages:
      - kitty
      - jq
      - fd-find
      - ripgrep

  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
      become: true
