---
- name: metz's machine configuration
  hosts: localhost
  connection: local

  vars:
    packages:
      - bat
      - chromium-browser
      - fd-find
      - gh
      - git
      - git-delta
      - jq
      - kitty
      - neovim
      - ripgrep
      - shellcheck
      - tmux
      - zellij

  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
      become: true

    - name: Configure git
      ansible.builtin.include_tasks: tasks/git.yml

    - name: Configure kitty
      ansible.builtin.include_tasks: tasks/kitty.yml

    - name: Configure tmux
      ansible.builtin.include_tasks: tasks/tmux.yml

    - name: Configure neovim
      ansible.builtin.include_tasks: tasks/neovim.yml

    - name: Configure zellij
      ansible.builtin.include_tasks: tasks/zellij.yml
