---
- name: Install git packages
  ansible.builtin.dnf:
    name:
      - git
      - git-delta
      - gh
    state: present
  become: true

- name: Copy gitconfig
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/.gitconfig"
    dest: ~/.gitconfig
